source "https://rubygems.org"
gem 'activesupport'
gem 'activemodel'
#gem 'mail'
gem 'thin'
gem 'bunny'
#gem 'ib-ruby', path: '../ib-ruby/'
gem 'ib-ruby',  :git=> 'https://github.com/ib-ruby/ib-ruby.git'
gem 'camping' #, git: 'https://github.com/topofocus/camping.git'
gem 'markaby' #, git: 'https://github.com/markaby/markaby.git' 
