source "https://rubygems.org"
gem 'activesupport'
gem 'activemodel'
#gem 'mail'
gem 'webrick'
gem 'ox'
gem 'ib-api', :git=> 'https://github.com/ib-ruby/ib-api.git'
gem 'ib-extensions',  git: 'https://github.com/ib-ruby/ib-extensions.git'
gem 'ib-symbols'
gem 'camping' # , git: 'https://github.com/topofocus/camping.git'
gem 'markaby' # , git: 'https://github.com/markaby/markaby.git' 
