#! /bin/bash
SESSION=simple-monitorw
# tmux mit 256 Farbunterstützung, Loginshell und UTF8-Support verwenden
tmux='tmux -2 -l -u' #
# if the session is already running, just attach to it.
$tmux has-session -t $SESSION
if [ $? -eq 0 ]; then
	echo "Session $SESSION already exists. Attaching."
	sleep 1
	$tmux attach -t $SESSION
	exit 0;
fi

$tmux new-session -d -s $SESSION
$tmux new-window  -t $SESSION:0  -c '~/simple-monitor/'

$tmux split-window -d -t $SESSION:0 -v
$tmux select-layout main-horizontal
#$tmux split-window -d  -p 10 -t $SESSION:0 -h
#
$tmux send-keys -t 1 'cd ~/simple-monitor' enter C-l
$tmux send-keys -t 1 'rvm use 2.5' enter C-l
$tmux send-keys -t 1 'camping simple_monitor.rb -p 3333' enter C-l
tmux resize-pane -t 1 -U 10  enter
#
$tmux send-keys -t 0 'sleep 1' enter 
$tmux send-keys -t 0 'elinks' enter 
#
#
#$tmux send-keys -t 3 'workon my_virtualenv' enter C-l
#$tmux send-keys -t 3 'cd MyProject/webui/' enter
#$tmux send-keys -t 3 'brunch watch' enter
#
### Just a convenience shell
#$tmux send-keys -t 4 'workon my_virtualenv' enter C-l
$tmux select-pane -t $SESSION:0

$tmux	attach -t $SESSION
